### ISSUE TITLE
Text Colour for Example Code

### ISSUE THREAD

**Issue by onedeadear** [workshopper/learnyounode#381]
Running on Windows 8, using the command prompt or cmder (any theme), I cannot see some of the text unless I highlight it.

![capture1](https://cloud.githubusercontent.com/assets/6351172/11017154/6cb445c6-858e-11e5-9ac4-0c545cf61290.PNG)

The last line above should be:

    var fs = require("fs")

**Comment by AmitJoki** [comment]
Yes. I'm encountering the same problem too.

**Comment by Liam-Ryan** [comment]
As a workaround you can right-click and edit properties of the cmd prompt, in the colors tab select "Screen Background" and change it to a more suitable colour. The dark gray next to blue is ugly but functional

**Comment by martinheidegger** [comment]
Could you try to install 'npm i sysenv -g' and run it using 'sysenv --term-colors'

**Comment by jhealy86** [comment]
Looks like I should have looked around more before submitting an issue, I just put #385 up about this. It's not that easy to see in Powershell, either.

**Comment by jhealy86** [comment]
@martinheidegger I took screenshots of both the Command Prompt and Powershell for you, both on default settings on Windows 10.
* [Command Prompt](http://imgur.com/a/8vsnu/)
* [Powershell](http://imgur.com/a/EXFSj)

**Comment by martinheidegger** [comment]
Awesome! Thanks! Does the Windows terminal have other "default themes"?

**Comment by jhealy86** [comment]
Not really in the sense that Linux terminals do. You can change the colors of the background and the text, and change the font if you really feel like doing some registry editing, but it's not a unified thing where you can set "Solaris" and have it change everything.

**Comment by Arnie97** [comment]
Snapshots with default terminal settings on elementaryOS:
![learnyounode verify](https://cloud.githubusercontent.com/assets/10341686/11619672/b836d55e-9ce5-11e5-9ea5-b3917fd379bb.png)
![sysenv --term-colors](https://cloud.githubusercontent.com/assets/10341686/11619686/d0c056cc-9ce5-11e5-8c16-a837dcfd8c7a.png)

**Comment by Arnie97** [comment]
Results with Linux xterm:
![learnyounode verify](https://cloud.githubusercontent.com/assets/10341686/11619873/af8e46ba-9ce7-11e5-9e20-782244226907.png)
![sysenv --term-colors](https://cloud.githubusercontent.com/assets/10341686/11619874/b3b46cb0-9ce7-11e5-8720-30940e6320fd.png)

**Comment by jthoms1** [comment]
I have just piped the output through the strip-ansi-cli module to get around the issue. Could be helpful if this is blocking progress.  We had alot of reports of this at our NodeSchool.

https://www.npmjs.com/package/strip-ansi-cli

**Comment by kokizzu** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/1061610/11708294/3cf6ab3c-9f40-11e5-94c0-ddb3c048115c.png)

**Comment by kokizzu** [comment]
+1 using white doesn't help also..

![image](https://cloud.githubusercontent.com/assets/1061610/11708580/0a7b9084-9f43-11e5-82c4-06e8423121c3.png)

**Comment by psalmody** [comment]
+1 Can't see any of the functions or code examples in windows cmd or powershell

**Comment by martinheidegger** [comment]
I published the latest version of learnyounode with a few updated dependencies after suggestions of @sindresorhus - It would be very awesome if you could verify the current state of learnyounode colors

**Comment by AntoniosHadji** [comment]
I'm still seeing this error with solarized color scheme on gnome-terminal in Ubuntu 14.04

**Comment by martinheidegger** [comment]
@AntoniosHadji If you clone msee you could test the colors used for Ubuntu and see what colors would be good for Ubuntu.

**Comment by AntoniosHadji** [comment]
@martinheidegger I switched my terminal theme to the standard Ubuntu colors and all text displays clearly.  It only breaks on my system when using solarized color scheme created from this gist: https://gist.github.com/codeforkjeff/1397104#file-solarize-sh.

**Comment by martinheidegger** [comment]
@AntoniosHadji A bug of solarized?

**Comment by AntoniosHadji** [comment]
@martinheidegger Possibly.  The background color is also contained in the pallette.  Perhaps that is what is causing the error in this solarized theme for gnome-terminal.  The text is using the same color as the background.  Highlighting the text does not show the text, only switching to a the original Ubuntu theme works for me.  I did not test other terminal schemes.

**Comment by martinheidegger** [comment]
In ubuntu it seems like solarized has a bug for a certain terminal color with the solarized theme. I just published a new version of msee (And workshopper-adventure) that should fix this issue on our side. Could you run `npm i learnyounode@latest -g` and see if the error persists?

**Comment by AntoniosHadji** [comment]
Yes, it works now.  The full text is visible.

**Comment by martinheidegger** [comment]
👍
